### ISSUE TITLE
Need OnReady?

### ISSUE THREAD

**Issue by GeorgeS2019** [RedouxG/SGT#2]
### Topic [OnReady ](https://github.com/godotengine/godot-proposals/issues/2425)for c#

It took a long time delay before the loaded `TestNode.tscn` is Ready to set 

`shouldBe10 = 10;`

https://github.com/RedouxG/SGT/blob/a495933f9bfa81c8018b73a28773dff700a7d13e/Examples/SceneTest.cs#L19

**Comment by RedouxG** [comment]
Sure, fixed. I had a very bad way of awaiting for test to be finished so the node was never actually doing anything and was instead blocked in `_PhysicsProcess`. Got rid of this await and now it works fine (takes 13ms for me to pass). I will make some other way of async exception reporting in the async runner
