### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by GeorgeS2019** [RedouxG/SGT#3]
> TODO:
> 
> Make GUI more pleasant to look at.
> Standarize output, possibly to XML format similar to other testing frameworks.

Do look at either 
- GodotXUnit  (better)
- NURF

**Comment by RedouxG** [comment]
Introduced xml format to tests, results are saved as a list of Message objects representing all test results. For now its just a basic form of xml output, but will make this more advanced in the future.
